# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
