# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20160305_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
